allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c88aa00e-a921-4198-96d9-4dc556fb1053:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-13T21:23:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9d7aa2c-f6f0-4606-a612-95c1941e7828
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T20:34:00+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3c05f413-8c7c-4f82-a256-ab4dd380ded7
            userCondition: null
          -
            dateAdded: '2026-04-20T20:34:00+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: 64b80823-ff24-49a5-ae25-4e1f79f7e596
            userCondition: null
          -
            dateAdded: '2026-04-18T23:37:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 47ce6d72-7761-41e0-bbb4-a0609649a858 # Bild
            handle: heroImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8db9e764-d160-4952-97f1-8de17c417be9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T20:34:00+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5907f1cc-88f9-4a3a-8000-d1817e96543c
            userCondition: null
          -
            dateAdded: '2026-04-20T20:34:00+00:00'
            elementCondition: null
            heading: Intro
            type: craft\fieldlayoutelements\Heading
            uid: cf63b592-a29b-4dcb-a769-5cea1f7d532d
            userCondition: null
          -
            dateAdded: '2026-04-20T20:34:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfe51714-3791-43e4-82d1-0bf8198689e7 # Text
            handle: introHead
            instructions: null
            label: Head
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1a82704-a6ea-4d03-b2c4-a97e89de8a3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T20:34:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfe51714-3791-43e4-82d1-0bf8198689e7 # Text
            handle: introText
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c131d1c-68b3-4a90-841c-73d8200a6b86
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-20T20:34:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfe51714-3791-43e4-82d1-0bf8198689e7 # Text
            handle: introInfotext
            instructions: null
            label: Infotext
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cbbe8d1-22df-4abe-aa2f-cfa1537916cc
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: f30a411b-bbbf-42a1-b09f-04576af27933
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-19T10:33:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3effc824-02d3-4f76-8421-f1c690b6b1c7 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cd3f276-f6cc-4cd9-8892-922c0a5a8d11
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bfb15313-b8c3-44d8-8d94-4cfbda633e10
        userCondition: null
    thumbFieldKey: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
