allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c88aa00e-a921-4198-96d9-4dc556fb1053:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-13T21:23:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9d7aa2c-f6f0-4606-a612-95c1941e7828
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-13T21:37:19+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfe51714-3791-43e4-82d1-0bf8198689e7 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72ff2aa1-c8ed-49df-a59f-1d7516980fcf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-18T23:37:21+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 47ce6d72-7761-41e0-bbb4-a0609649a858 # Bild
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8db9e764-d160-4952-97f1-8de17c417be9
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: f30a411b-bbbf-42a1-b09f-04576af27933
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-19T10:33:32+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3effc824-02d3-4f76-8421-f1c690b6b1c7 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cd3f276-f6cc-4cd9-8892-922c0a5a8d11
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bfb15313-b8c3-44d8-8d94-4cfbda633e10
        userCondition: null
    thumbFieldKey: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
