allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9c5d890e-98e2-4d15-b6da-ba314fe89af8:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-19T21:55:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d9f438f2-7569-4176-abf8-235eb084cf4a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T20:53:06+00:00'
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: ef6a5e27-79de-4823-8b77-2c1b44848ba3
            userCondition: null
          -
            dateAdded: '2026-05-13T20:53:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 47ce6d72-7761-41e0-bbb4-a0609649a858 # Bild
            handle: heroImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cd11ad7-0374-4251-8bca-85de00922adc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T21:58:19+00:00'
            elementCondition: null
            heading: Inhalt
            type: craft\fieldlayoutelements\Heading
            uid: 5b333aa0-f414-42f8-b565-763b833004a9
            userCondition: null
          -
            dateAdded: '2026-07-06T07:41:47+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 72039248-dd27-48ca-8812-ed3e3dfef377 # Headline
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68e05b9c-5825-40c3-9da7-2a5edecaf414
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T22:38:43+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c4aaedc7-1bf0-4d39-9731-76bd91a97e45 # Teammitglieder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56925ab8-4d90-48eb-be59-826e177cadac
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 8b2740df-4273-473d-b408-992979dd7c3b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-13T20:53:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 47ce6d72-7761-41e0-bbb4-a0609649a858 # Bild
            handle: teaserImage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f89dac27-61df-4a7b-913a-7e741536e09e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-30T21:58:19+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfe51714-3791-43e4-82d1-0bf8198689e7 # Text
            handle: teaserText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b989b89e-9875-4d40-b247-9b7787cbfa8c
            userCondition: null
            warning: null
            width: 100
        name: Teaser
        uid: 07e2c166-4ea8-44f9-baa0-251e42f87482
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-19T21:59:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3effc824-02d3-4f76-8421-f1c690b6b1c7 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e56f20f5-a889-4b28-b1eb-d92ed1b3012d
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bfa9fc76-f58a-454a-8b9c-8abce149cad9
        userCondition: null
    thumbFieldKey: 'layoutElement:2cd11ad7-0374-4251-8bca-85de00922adc'
handle: team
hasTitleField: true
icon: people-group
name: Team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
