allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  70ccc77b-e604-41df-8ae3-fd5f87fc5233:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:d1988985-6cc4-422e-baee-39b5fdc73a83'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-24T22:44:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Zeitraum
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a7bf3838-d144-4f74-9a80-3ad058b894c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-24T22:49:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cfe51714-3791-43e4-82d1-0bf8198689e7 # Text
            handle: occupation
            instructions: null
            label: Tätigkeit
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1988985-6cc4-422e-baee-39b5fdc73a83
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: bb6c8e70-4cad-4540-b399-5a96fe6fbb6a
        userCondition: null
    thumbFieldKey: null
handle: vitaItem
hasTitleField: true
icon: circle-small
name: Station
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
