altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fd9feb4f-ac1f-421c-b5e2-23cbfe29a2ab:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-18T23:33:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 268196e7-8979-41ec-a642-ece774797a2c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2026-04-18T23:35:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 7366141e-e2ec-4f05-ac70-046530b377e3
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 46e8127e-16e8-4f48-8a03-5829634a3624
        userCondition: null
    thumbFieldKey: null
fs: images
handle: images
name: Bilder
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
