columnSuffix: null
handle: files
instructions: null
name: Dateien
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - excel
    - compressed
    - pdf
    - powerpoint
    - text
    - word
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:90d2531c-9d53-43e2-b50a-72d5a77e5c94' # Dateien
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:f0ce45d1-0845-466f-bfba-3b658bb597c8' # Bilder
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:90d2531c-9d53-43e2-b50a-72d5a77e5c94' # Dateien
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
