columnSuffix: null
handle: teamMembers
instructions: null
name: Teammitglieder
searchable: true
settings:
  createButtonLabel: Hinzufügen
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 2fcf31e7-756a-4bfe-9d0f-c2957d609d32 # Kategorie
        -
          - group
          - Allgemein
    -
      __assoc__:
        -
          - uid
          - cc4cbfb3-ec2c-490a-99d9-26c105b0467d # Teammitglied
        -
          - group
          - Allgemein
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
