fieldLayouts:
  e07e40d0-7a6b-4f93-89c7-d39552372fc3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-20T10:09:20+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: be2dbd1e-b57d-4114-a1cc-84afe541c5a7 # Link
            handle: doctolibLink
            instructions: null
            label: Doctolib-Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 888a9d80-8439-4e26-b011-03922127a0e0
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: ab9ff4f2-3096-479e-a707-a7bbaacf8086
        userCondition: null
    thumbFieldKey: null
handle: doctolibLink
name: Doctolib-Link
sortOrder: 1
