fieldLayouts:
  a006213c-fcbf-4da2-ae54-8ae1c95a5f56:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-19T19:17:50+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a106464c-9e4c-4464-9a7d-3890f652ec32 # Navigation-Items
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5494f79d-ef6c-4e14-81d7-11f751772375
            userCondition: null
            warning: null
            width: 100
        name: Navigation
        uid: 914d0fac-9170-4965-84cb-7df59afb515d
        userCondition: null
    thumbFieldKey: null
handle: navigation
name: Navigation
sortOrder: 2
