defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: eb83d5d1-d43a-43db-b4ef-3fdfed85a470 # Textseite
handle: imprint
maxAuthors: 1
minAuthors: 1
name: Impressum
previewTargets:
  -
    label: Frontend
    refresh: ''
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  954a6c0c-c857-4ea0-96ce-bfbe209e21fe: # Lungenfachärzte in der Bertoldstrasse
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: impressum
type: single
